### PR TITLE
Fix osx arm64 build

### PR DESCRIPTION
**Pull request by jeongseok-meta**
The ARM OSX build was enabled by https://github.com/conda-forge/pymcubes-feedstock/pull/4, but it never succeeded in building. This PR aims to fix the build error.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
Hi @willGraham01, could you please review this PR when you have a chance? Thanks!

**Review by willGraham01 — APPROVED** [review]
Changes to the recipe look good :+1: 

Not quite sure what the changes to the hidden files are doing, but I assume this is the conda-forge admin re-rendering.

Build seems to work, and I can fork & clone this branch and successfully run `build-locally`, so looks good to merge.

**Comment by jeongseok-meta** [comment]
> Not quite sure what the changes to the hidden files are doing, but I assume this is the conda-forge admin re-rendering.

Yup, exactly. Thanks for local testing and merging this PR!

**Pull request merged**
